# Generated by Django 3.2.8 on 2025-01-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_imageheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageheader',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
