# Generated by Django 3.2.8 on 2025-01-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_imageheader_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageheader',
            name='image',
            field=models.ImageField(upload_to='headers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
