# Generated by Django 3.2.8 on 2025-01-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_imagenspot_textspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('boton', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
