# Generated by Django 3.2.8 on 2025-01-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_secciondos_seccionuno_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Archivo MP4'),
        ),
    ]
