# Generated by Django 3.2.8 on 2025-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Video'),
        ),
    ]
