# Generated by Django 3.2.8 on 2025-02-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_video_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenspot',
            name='image_cuatro',
            field=models.ImageField(blank=True, null=True, upload_to='spots'),
        ),
        migrations.AddField(
            model_name='imagenspot',
            name='image_tres',
            field=models.ImageField(blank=True, null=True, upload_to='spots'),
        ),
        migrations.AddField(
            model_name='imagenspot',
            name='imagen_dos',
            field=models.ImageField(blank=True, null=True, upload_to='spots'),
        ),
    ]
