# Generated by Django 3.2.8 on 2025-02-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20250220_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenspot',
            old_name='image_cuatro',
            new_name='imagen_cuatro',
        ),
        migrations.RenameField(
            model_name='imagenspot',
            old_name='image_tres',
            new_name='imagen_tres',
        ),
    ]
