# Generated by Django 3.2.8 on 2025-02-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20250220_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='textspot',
            name='subtitulo_dos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textspot',
            name='subtitulo_segunda_seccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textspot',
            name='subtitulo_tres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textspot',
            name='subtitulo_uno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textspot',
            name='titulo_dos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textspot',
            name='titulo_tres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textspot',
            name='titulo_uno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
