# Generated by Django 3.2.8 on 2025-02-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20250221_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciondos',
            name='subtitulo_dos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seccionuno',
            name='subtitulo_uno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
